version: '3.8'

services:
  app:
    build: .
    container_name: go-app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=ShowRater
    command: air

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ShowRater
    ports:
      - "5432:5432"
    volumes:
      - ./.database:/var/lib/postgresql/data
      - ./data/scripts:/docker-entrypoint-initdb.d

  tailwind:
    image: node:18
    container_name: tailwind
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    command: ["npx", "tailwindcss", "-i", "css/styleSource.css", "-o", "css/style.css", "--watch"]

