FROM node

WORKDIR /app

COPY package.json ./

RUN npm install -g npm && \
    npm install

RUN npm install -g tailwindcss

COPY tailwind.config.js ./

CMD ["npx", "tailwindcss", "-i", "./css/styleSource.css", "-o", "./css/style.css", "--watch"]

